### ISSUE TITLE
default port 80 not 443?

### ISSUE THREAD

**Issue by mbonig** [chiefbiiko/dynamodb#11]
When establishing the connection in the derive_config:

https://github.com/chiefbiiko/dynamodb/blob/master/client/derive_config.ts#L47

you are assuming a default port of 80. DynamoDB requires a 443 so why is that not the default?

**Comment by chiefbiiko** [comment]
thanks, definitely need to change that!

**Comment by mbonig** [comment]
https://github.com/chiefbiiko/dynamodb/pull/12

**Comment by hayd** [comment]
In deno-lambda had to do this in order to support both regular use and test: https://github.com/hayd/deno-lambda/blob/master/example-serverless/client.ts#L8

**Comment by hayd** [comment]
close?

**Comment by mbonig** [comment]
appears resolved now in v0.3.0
