### ISSUE TITLE
Error when package getting installed

### ISSUE THREAD

**Issue by y2kshane** [chiefbiiko/dynamodb#19]
I'm getting below error when dynamodb package getting installed..

`PS G:\AWS Workspace\deno-rest> deno run --allow-net .\denoserver.ts
Download https://denopkg.com/chiefbiiko/dynamodb/mod.ts
Download https://raw.githubusercontent.com/chiefbiiko/dynamodb/master/mod.ts
Compile https://raw.githubusercontent.com/chiefbiiko/dynamodb/master/mod.ts
Download https://raw.githubusercontent.com/chiefbiiko/dynamodb/master/client/mod.ts
Download https://raw.githubusercontent.com/chiefbiiko/dynamodb/master/util.ts
Download https://raw.githubusercontent.com/chiefbiiko/dynamodb/master/util.ts
Download https://raw.githubusercontent.com/chiefbiiko/dynamodb/master/client/aws_signature_v4.ts
Download https://raw.githubusercontent.com/chiefbiiko/dynamodb/master/client/base_op.ts
Download https://raw.githubusercontent.com/chiefbiiko/dynamodb/master/client/derive_config.ts
Download https://raw.githubusercontent.com/chiefbiiko/dynamodb/master/client/create_headers.ts
Download https://raw.githubusercontent.com/chiefbiiko/dynamodb/master/client/translator.ts
Download https://raw.githubusercontent.com/chiefbiiko/dynamodb/master/deps.ts
Download https://denopkg.com/chiefbiiko/std-encoding@v1.0.0/mod.ts
Download https://denopkg.com/chiefbiiko/get-aws-config@v0.3.5/mod.ts
Download https://denopkg.com/chiefbiiko/hmac@v1.0.2/mod.ts
Download https://deno.land/x/base64@v0.2.0/mod.ts
Download https://denopkg.com/chiefbiiko/sha256@v1.0.2/mod.ts
Download https://raw.githubusercontent.com/chiefbiiko/std-encoding/v1.0.0/mod.ts
Download https://raw.githubusercontent.com/chiefbiiko/hmac/v1.0.2/mod.ts
Download https://raw.githubusercontent.com/chiefbiiko/sha256/v1.0.2/mod.ts
Download https://raw.githubusercontent.com/chiefbiiko/get-aws-config/v0.3.5/mod.ts
Download https://deno.land/x/base64/base64url.ts
Download https://deno.land/x/base64/base.ts
Download https://raw.githubusercontent.com/chiefbiiko/hmac/v1.0.2/deps.ts
Download https://denopkg.com/chiefbiiko/sha1@v1.0.3/mod.ts
Download https://denopkg.com/chiefbiiko/sha512@v1.0.3/mod.ts
Download https://raw.githubusercontent.com/chiefbiiko/sha1/v1.0.3/mod.ts
Download https://raw.githubusercontent.com/chiefbiiko/sha512/v1.0.3/mod.ts
Download https://raw.githubusercontent.com/chiefbiiko/sha1/v1.0.3/deps.ts
Download https://raw.githubusercontent.com/chiefbiiko/sha256/v1.0.2/deps.ts
Download https://raw.githubusercontent.com/chiefbiiko/sha512/v1.0.3/deps.ts
Download https://deno.land/x/base64@v0.2.0/base.ts
Download https://raw.githubusercontent.com/chiefbiiko/dynamodb/master/client/base_fetch.ts
Download https://raw.githubusercontent.com/chiefbiiko/dynamodb/master/api/mod.ts
Download https://raw.githubusercontent.com/chiefbiiko/dynamodb/master/api/api.ts
Download https://raw.githubusercontent.com/chiefbiiko/dynamodb/master/api/collection.ts
Download https://raw.githubusercontent.com/chiefbiiko/dynamodb/master/api/operation.ts
Download https://raw.githubusercontent.com/chiefbiiko/dynamodb/master/api/shape.ts
Download https://raw.githubusercontent.com/chiefbiiko/dynamodb/master/client/converter.ts
Download https://raw.githubusercontent.com/chiefbiiko/dynamodb/master/client/create_cache.ts
error TS2339: Property 'dir' does not exist on type 'typeof Deno'.
const HOME: string = Deno.dir("home") ?? "";
                          ~~~
    at https://raw.githubusercontent.com/chiefbiiko/get-aws-config/v0.3.5/mod.ts:11:27

error TS2349: This expression is not callable.
  Type '{ get(key: string): string | undefined; set(key: string, value: string): void; toObject(): { [index: string]: string; }; }' has no call signatures.
  const ENV: { [key: string]: any; } = _opts.env ? Deno.env() : {};
                                                        ~~~
    at https://raw.githubusercontent.com/chiefbiiko/get-aws-config/v0.3.5/mod.ts:90:57

Found 2 errors.`

**Comment by chiefbiiko** [comment]
should be fixed in [`dynamodb@v1.0.0`](https://github.com/chiefbiiko/dynamodb/releases/tag/v1.0.0)
