### ISSUE TITLE
Support 1.0.0

### ISSUE THREAD

**Issue by hayd** [chiefbiiko/dynamodb#20]
There have been a bunch of breaking code changes which affect dynamodb (and dependencies).

Would be great to have this working for 1.0.0 !

**Comment by artoliukkonen** [comment]
I've tested that this library supports 1.0.0. The only thing that needs to be done is to update `get-aws-config` dependency. Ping @chiefbiiko . That dependency at least in my tests still requires this patch to be merged to get it working https://github.com/chiefbiiko/get-aws-config/pull/2

**Comment by chiefbiiko** [comment]
@hayd @artoliukkonen 
just released [`dynamodb@v1.0.0`](https://github.com/chiefbiiko/dynamodb/releases/tag/v1.0.0)
