### ISSUE TITLE
How to putItem or updateItem with conditional expression?

### ISSUE THREAD

**Issue by besingamkb** [chiefbiiko/dynamodb#24]
Hi. first of all im not really good at deno, typescript and dynamodb. i just want to learn something new. so I manage to connect and put an item to my table. but I wonder how will I do it with conditional expression. I look on the docs and test file but I cant find any example on how to do it using this package.

It would be great if anyone can help and show me how can I updateItem or putItem with conditional express with its values.

thank you in advance

**Comment by chiefbiiko** [comment]
have a look at the test case added in this pr #26

**Comment by besingamkb** [comment]
yes i will check this. thank you
