### ISSUE TITLE
possible to make this lib like dynamoose?

### ISSUE THREAD

**Issue by yeukfei02** [chiefbiiko/dynamodb#25]
`dynamoose` is for node to use dynaomodb in serverless lambda.

I see this lib use all like native aws js sdk to call with dynaomodb...
I am looking for something like deno version of `dynamoose`

Thanks.

**Comment by chiefbiiko** [comment]
not sure what functionality exactly you are looking for.
i purposely designed `dynamodb`'s api surface simple - each call corresponds to an official aws dynamodb api
anyways, this module does not try to emulate dynamoose (or any other lib)
