### ISSUE TITLE
error deriving credentials

### ISSUE THREAD

**Issue by mbonig** [chiefbiiko/dynamodb#9]
Right now I have access keys setup in a standard (default) profile in my ~/.aws/config and ~/.aws/credentials files. When I use the [get-aws-config](https://denopkg.com/chiefbiiko/get-aws-config/mod.ts) dependency directly I can see it properly retrieving all my credential information correctly. However, when trying to `.createClient` I get this error:

`error: Uncaught Error: unable to derive aws config`

Here at this line: https://github.com/chiefbiiko/dynamodb/blob/master/client/derive_config.ts#L27

Looking through the current code it looks like the derive_config.ts is expecting access key and secret to sit on a "credentials" field, where 'got' currently returns those directly on the return object.

**Comment by chiefbiiko** [comment]
thanks, good catch!
if u r currently on this make sure to update `dynamodb/deps.ts` to import `get-aws-config@v0.3.2`
that version has some related patches
but definitely, the `got.credentials` thing is just wrong

**Comment by mbonig** [comment]
Submitted a PR:

https://github.com/chiefbiiko/dynamodb/pull/10/files

Please review my comments. I think there are more changes that need to be made first.

**Comment by chiefbiiko** [comment]
Fixed in v0.3.0
